### ISSUE TITLE
Ubuntu PPA Down + Compile Instructions Old

### ISSUE THREAD

**Issue by halsafar** [g2p/blocks#17]
I know this isn't a coding issue but I need some assistance with your project here and its looks to be exactly what we need.  I am having a hell of a time installing this on Ubuntu 12.04. 

 I have a raid5 here which has gained an extra 30% space but it was partitioned without using LVM.  We need that now.  We do have a offsite mirror of the data so we could destroy and convert but an in-place conversion would be much better.

Tried to install via PPA instructions on github.  apt-get update says the URL for the new PPA is dead.

Tried to install the requires libs manually and compile from source but things like python3-pip and others are missing in Ubuntu 12.04.

Any advice?

**Comment by g2p** [comment]
The PPA is built for Ubuntu 13.10 and newer. python3-pip appears in 13.04, and I think the PPA contains older versions of the packages built for that release. If you keep an older release, installing the required versions of Pip, Python, Augeas is your responsibility. Note that you can run blocks from a LiveCD, read the relevant bits of the readme.
