### ISSUE TITLE
Error converting to PV

### ISSUE THREAD

**Issue by John-Gee** [g2p/blocks#2]
Hello,

I was looking at a way to merge my current ext4 partition into an existing VG and found your great tool.

Alas, I ran into an issue while running it:

Copying 4194304 bytes from pos 0 to pos 1935063121920... ok
Preparing LVM metadata... device-mapper: reload ioctl on synthetic-c2a39272-0703-11e3-b675-d85d4ca3aa01 failed: Invalid argument
Command failed
Command ['losetup', '-d', '--', '/dev/loop0'] has failed with status 1
Standard output:

Standard error:
losetup: /dev/--: detach failed: No such file or directory

I am not sure what to do here, am I missing a dependency or is anything else wrong?

Thanks!

**Comment by g2p** [comment]
I think you just have an old version of util-linux (edit: ok, too new :P). What's your Linux distribution, what does `dpkg -s util-linux` (or equivalent) say?

**Comment by John-Gee** [comment]
wow that was super fast, thank you!

pacman -Qi util-linux 
Name           : util-linux
Version        : 2.23.2-1

It seems pretty current no?

I am running full fsck on the partition just in case...

**Comment by g2p** [comment]
I tweaked the losetup invocation in master, can you try again?

**Comment by John-Gee** [comment]
It looks the same:
The filesystem (ext4) leaves enough room, no need to shrink it
Copying 4194304 bytes from pos 0 to pos 1935063121920... ok
Preparing LVM metadata... device-mapper: reload ioctl on synthetic-736c1730-0710-11e3-a74d-d85d4ca3aa01 failed: Invalid argument
Command failed

by the way, here is my command in case... :
blocks to-lvm --join=VG /dev/sda4

(VG being the name of my vg...)

**Comment by g2p** [comment]
OK, I only fixed the losetup cleanup, there's still something wrong with the dmsetup invocation. The `troubleshooting/dm-table` branch will print the dm table, maybe dm will have some messages in dmesg as well.

**Comment by John-Gee** [comment]
In dmesg:
[   73.918958] loop: module loaded
[   73.929763] device-mapper: table: 254:2: linear: dm-linear: Device lookup failed
[   73.929767] device-mapper: ioctl: error adding target to table

I am not sure what you mean by troubleshooting though.

**Comment by g2p** [comment]
Try `git remote update; git checkout troubleshooting/dm-table`; that version will print extra info.

**Comment by John-Gee** [comment]
Oh another git branch:

The filesystem (ext4) leaves enough room, no need to shrink it
Copying 4194304 bytes from pos 0 to pos 1935063121920... ok
Preparing LVM metadata... TABLE '0 3779427643 error\n'
TABLE '0 8192 linear /dev/loop0 0\n8192 3779427643 linear /dev/mapper/rozeros-3d7ead86-0715-11e3-a60a-d85d4ca3aa01 0\n'
device-mapper: reload ioctl on synthetic-3d7eb1e6-0715-11e3-a60a-d85d4ca3aa01 failed: Invalid argument
Command failed

**Comment by g2p** [comment]
It seems like dm can't find the /dev/mapper/rozeros-\* device (254 would be device-mapper devices on your machine). I don't get it, but I'll try to reproduce this in an Arch VM.

**Comment by John-Gee** [comment]
hmmm I don't see any of that unless it is somehow hidden:

> l /dev/mapper/ 
> VG-medias@  control

**Comment by g2p** [comment]
`/dev/mapper` is supposed to get cleaned up either way. I haven't been able to reproduce the bug, everything worked inside my Arch VM (aside from udev not poking lvmetad when testing on loopback, but that has no impact on conversion). I've added ipdb support to the troubleshooting branch:

```
pip install --user ipdb
```

Then pull the branch and run that.
When you land inside a debugger, you can use another shell to run:

```
sudo blkid -p /dev/loop0
sudo blkid -p /dev/mapper/rozeros*
```

Which should confirm which of the two devices is missing.

**Comment by John-Gee** [comment]
#blkid -p /dev/loop0
#blkid -p /dev/mapper/rozeros*
zsh: no matches found: /dev/mapper/rozeros*

**Comment by g2p** [comment]
I've pushed a version that tries to create rozeros\* with udev and then without it, please give it a test.

**Comment by John-Gee** [comment]
That worked!
Awesome!

**Comment by John-Gee** [comment]
Hmmmmmm

Actually it failed at merging with my VG, which could be my fault.

Rerunning block says it already is a PV which seems.
pvscan does not display anything about it tough, I am not sure what to do...

> /root/.local/lib/python3.3/site-packages/IPython/frontend.py:30: UserWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
>   warn("The top-level `frontend` package has been deprecated. "
> The filesystem (ext4) leaves enough room, no need to shrink it
> Copying 4194304 bytes from pos 0 to pos 1935063121920... ok
> Preparing LVM metadata... TABLE '0 3779427643 error\n'
> TABLE '0 8192 linear /dev/loop0 0\n8192 3779427643 linear /dev/mapper/rozeros-3ebad4e2-0790-11e3-9b2b-d85d4ca3aa01 0\n'
> ok
> If the next stage is interrupted, it can be reverted with:
>     dd if=/dev/sda4 of=/dev/sda4 bs=4194304 count=1 skip=461355 conv=notrunc
> Installing LVM metadata... ok
> LVM conversion successful!
> Command ['lvm', 'vgmerge', '--', 'VG', '3e83842e079011e39b2bd85d4ca3aa01'] has failed with status 5
> Standard output:
> 
> Standard error:
>   Volume group "3e83842e079011e39b2bd85d4ca3aa01" not found
> 
> CalledProcessError(5, ['lvm', 'vgmerge', '--', 'VG', '3e83842e079011e39b2bd85d4ca3aa01'], '')

**Comment by John-Gee** [comment]
I cleaned up and retried without merging with my existing VG and it passed:

> #blocks to-lvm /dev/sda4
> /root/.local/lib/python3.3/site-packages/IPython/frontend.py:30: UserWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
>   warn("The top-level `frontend` package has been deprecated. "
> The filesystem (ext4) leaves enough room, no need to shrink it
> Copying 4194304 bytes from pos 0 to pos 1935063121920... ok
> Preparing LVM metadata... TABLE '0 3779427643 error\n'
> TABLE '0 8192 linear /dev/loop0 0\n8192 3779427643 linear /dev/mapper/rozeros-a2fe8c94-0792-11e3-80f6-d85d4ca3aa01 0\n'
> ok
> If the next stage is interrupted, it can be reverted with:
>     dd if=/dev/sda4 of=/dev/sda4 bs=4194304 count=1 skip=461355 conv=notrunc
> Installing LVM metadata... ok
> LVM conversion successful!
> Volume group name: sda4
> Logical volume name: 1stDrive
> Filesystem uuid: bd1adbfd-3956-44d3-bfea-b75265a57f87

But still I cannot find the new PV:

> #pvscan
>   PV /dev/sdb1   VG VG   lvm2 [3.64 TiB / 0    free]
>   Total: 1 [3.64 TiB] / in use: 1 [3.64 TiB] / in no VG: 0 [0   ]

 or the new VG:

> #vgscan
>   Reading all physical volumes.  This may take a while...
>   Found volume group "VG" using metadata type lvm2

**Comment by g2p** [comment]
pvscan doesn't seem to work well since the introduction of `lvmetad`, I had the same problem in my Arch VM.  Use:

```
pvscan --cache /dev/sda4
```

**Comment by John-Gee** [comment]
oh yes that worked!
