### ISSUE TITLE
Shrinking strategy fails with 1M free

### ISSUE THREAD

**Issue by mullrich** [g2p/blocks#27]
I'm trying to convert a partition to bcache. I created the partition some time ago using `parted -s -a opt /dev/sdx mklabel gpt mkpart primary 1m 100%`, so there should be 1M in front. Why does bcache fail in this case? I am aware of issue #1, but wouldn't have thought this was the problem here. Error message is `The range we want to reserve overlaps with the start of a reserved area at [0, 33] (metadata), the shrinking strategy will not work.` I'm on Ubuntu 14.04 (3.19), Python 3.4. Thanks!

**Comment by g2p** [comment]
There's GPT metadata at the start of the partition, which cannot be removed.
If this is a new system, start the partition at 2M, otherwise you could use the bcache on LVM approach.
