### ISSUE TITLE
problem during installation on ubuntu live 13.04 & 13.10

### ISSUE THREAD

**Issue by fvigotti** [g2p/blocks#3]
when i run 
sudo apt-get install python3-blocks bcache-tools

i get the error : 
The following packages have unmet dependancies:
 python3-blocks : Depends: python3-maintboot but it is not going to be installed

E: Unable to  correct problems, you have held broken packages.

this come from both the daily build of ubuntu 13.10 and current release of 13.04

edit:
i've tryed now also with 32 bit versions, same error occurr.. 
i don't know why but i has been able to install into this virtual image : http://virtualboximages.com/Ubuntu+Gnome+13.10+i386+VirtualBox+VDI+Virtual+Appliance

but i need the software works on a live bootable iso so i can boot from usb and use it .

thanks

**Comment by g2p** [comment]
Oh, you're right. maintboot depends on supermin, which is in universe, and not enabled by default on livecd. You can use software properties to enable it. I'll add supermin to the ppa as a workaround.

**Comment by fvigotti** [comment]
perfect, thanks :)

**Comment by kislyuk** [comment]
I am still experiencing this in 14.04 after following the instructions in the readme. Any advice?

**Comment by kislyuk** [comment]
OK - this looks different:

```
# apt-get install python3-maintboot
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-maintboot : Depends: python3.3 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kislyuk** [comment]
Trusty, of course, ships with python3.4.
