### ISSUE TITLE
ValueError: Unable to store text at node! when converting to bcache

### ISSUE THREAD

**Issue by garrettngarcia** [g2p/blocks#4]
After installing LVM on the HDD using blocks, I used make-bcache on a live CD to create a cache set,and ran the following:

ubuntu@ubuntu:~$ sudo blocks to-bcache /dev/mapper/vg.sda6-sda6 --join=d2989864-2169-4031-8030-9ba4b37925fd
Will shrink the filesystem (ext4) by 4194304 bytes
Checking the filesystem before resizing it
e2fsck 1.42.5 (29-Jul-2012)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/mapper/vg.sda6-sda6: 185308/29515776 files (0.3% non-contiguous), 3050165/118045696 blocks
Copying the bcache superblock... ok
Loading LVM metadata... Traceback (most recent call last):
  File "/usr/bin/blocks", line 9, in <module>
    load_entry_point('blocks==0.1.3', 'console_scripts', 'blocks')()
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1856, in script_main
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1532, in main
    return args.action(args)
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1615, in cmd_to_bcache
    device=device, debug=args.debug, progress=progress, join=args.join)
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1378, in lv_to_bcache
    device=device, size=device.size, debug=debug, forward=False)
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1288, in rotate_lv
    aug.text_store('LVM.lns', '/raw/vgcfg', '/vg')
  File "/usr/lib/python3/dist-packages/augeas.py", line 232, in text_store
    raise ValueError("Unable to store text at node!")
ValueError: Unable to store text at node!

Running from a Ubuntu 13.04 64 bit live CD.  System is a Lenovo T430s w/ 500GB HDD (sda) and 16GB SSD (sdb).  Upgraded to 3.10.x kernel on the HDD install.  Let me know if you need more info.  Thanks in advance for the help.

UPDATE: output of vgcfgbackup and sudo cat /etc/lvm/backup/vg.sda6 |xsel -b:

ubuntu@ubuntu:~$ sudo vgcfgbackup
  Volume group "vg.sda6" successfully backed up.
ubuntu@ubuntu:~$ sudo cat /etc/lvm/backup/vg.sda6 |xsel -b

```
# Generated by LVM2 version 2.02.95(2) (2012-03-06): Fri Sep 20 21:17:12 2013

contents = "Text Format Volume Group"
version = 1

description = "Created *after* executing 'vgcfgbackup'"

creation_host = "ubuntu"    # Linux ubuntu 3.8.0-19-generic #29-Ubuntu SMP Wed Apr 17 18:16:28 UTC 2013 x86_64
creation_time = 1379711832  # Fri Sep 20 21:17:12 2013

vg.sda6 {
    id = "024296-2c20-3511-e3bc-7da4-4e31-419d04"
    seqno = 1
    format = "lvm2" # informational
    status = ["RESIZEABLE", "READ", "WRITE"]
    flags = []
    extent_size = 8192      # 4 Megabytes
    max_lv = 0
    max_pv = 0
    metadata_copies = 0

    physical_volumes {

        pv0 {
            id = "024248-ca20-3511-e3bc-7da4-4e31-419d04"
            device = "/dev/sda6"    # Hint only

            status = ["ALLOCATABLE"]
            flags = []
            dev_size = 944377856    # 450.314 Gigabytes
            pe_start = 8192
            pe_count = 115279   # 450.309 Gigabytes
        }
    }

    logical_volumes {

        sda6 {
            id = "02433f-b420-3511-e3bc-7da4-4e31-419d04"
            status = ["READ", "WRITE", "VISIBLE"]
            flags = []
            segment_count = 2

            segment1 {
                start_extent = 0
                extent_count = 1    # 4 Megabytes

                type = "striped"
                stripe_count = 1    # linear

                stripes = [
                    "pv0", 115278
                ]
            }
            segment2 {
                start_extent = 1
                extent_count = 115278   # 450.305 Gigabytes

                type = "striped"
                stripe_count = 1    # linear

                stripes = [
                    "pv0", 0
                ]
            }
        }
    }
}
```

**Comment by g2p** [comment]
Could you run

```
sudo cat /etc/lvm/backup/vg.sda6 |xsel -b
```

and paste it in this bug report? (run `vgcfgbackup` if it doesn't exist) Also, if you didn't need a livecd for the lvm conversion, you probably don't need it for the bcache conversion; the livecd is only necessary if you are unable to unmount the filesystem from your normal environment.

**Comment by garrettngarcia** [comment]
After filing the issue, I reinstalled and tried again.  I'm getting the same error.  I updated the original report to show the output from the latest run as well as the output from the command you suggested to run.  Let me know if you need any more information about the setup.  Thanks!

**Comment by g2p** [comment]
Could you try the latest commit? I think it was just an overly strict lexing rule.

**Comment by garrettngarcia** [comment]
Here's the output after the updates.  I don't see any errors, so that's a good sign.  I'll pop out the liveCD now and try booting from the HDD

```
ubuntu@ubuntu:~$  sudo blocks to-bcache /dev/mapper/vg.sda6-sda6 --join=d2989864-2169-4031-8030-9ba4b37925fd
The filesystem (ext4) leaves enough room, no need to shrink it
Copying the bcache superblock... ok
Loading LVM metadata... ok
Rotating the last extent to be the first... ok
```

**Comment by garrettngarcia** [comment]
It looks like there's still something wrong.  When I tried to boot, these are the errors that came up:

```
mount: mounting /dev/mapper/vg.sda6-sda6 on /root failed: Invalid argument
mount: mounting /dev on /root/dev failed: No such file or directory
mount: mounting /sys on /root/sys failed: No such file or directory
mount: mounting /proc on /root/proc failed: No such file or directory
Target filesystem doesn't have requested /sbin/init.
No init found. Try passing init=bootarg

BusyBox v1.20.2 (Ubuntu 1:1.20.0-8.1ubuntu1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) _
```

**Comment by g2p** [comment]
Your grub.cfg is invalid, it should contain the filesystem uuid rather than the VG path (there's something about it in the README). For now, you can edit by hand from the grub menu (hold shift, type e, root=/dev/bcache0 should work if it's your sole volume), and `sudo update-grub` will write the correct grub.cfg once you've booted.

**Comment by garrettngarcia** [comment]
I tried modifying grub to root=/dev/bcache0 and it still couldn't find it  I also added rootdelay=100 in case that would help, but it didn't.  Just to be sure, I started completely over, wiped the hard drive and went through all of the steps again, including setting up the grub file to use UUID's.  It still couldn't find the device and will only boot to the BusyBox prompt.  I tried booting to root=/dev/bcache0 again, but it still doesn't exist.  Which UUID should I be using in the grub file?  Do you have any other suggestions?  Nothing seems to be working.

**Comment by g2p** [comment]
I think I closed this one by mistake, sorry. I hope you managed to figure out something.

**Comment by garrettngarcia** [comment]
Yeah after your help in the bcache irpc channel (at least I think it was
you), everything is working great. Thanks again!
